# Generated by Django 4.2.11 on 2025-09-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='imageUrl',
            field=models.CharField(default="{% static 'auctions/defaultimg.png' %})", max_length=60),
        ),
    ]
