# Generated by Django 4.2.11 on 2025-09-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auctionlisting_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='name',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='num_stars',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='release_date',
        ),
        migrations.AddField(
            model_name='bid',
            name='amount',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
