# Generated by Django 4.2.11 on 2025-09-28 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_bid_name_remove_bid_num_stars_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='auctionId',
            new_name='auction',
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='userId',
            new_name='user',
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auctionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to='auctions.auctionlisting')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
