# Generated by Django 4.2.11 on 2025-09-28 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_rename_auctionid_bid_auction_rename_userid_bid_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='auctionId',
            new_name='auction',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='userId',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='auctionId',
            new_name='auction',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='userId',
            new_name='user',
        ),
    ]
