# Generated by Django 4.2.11 on 2025-09-28 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_rename_auctionid_comment_auction_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('user', 'auction')},
        ),
    ]
