# Generated by Django 4.2.11 on 2025-09-28 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_wishlist_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
